server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:file:~/workspace/event-driven-microservice/dataDB
    username: sa
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2


axon:
  serializer:
    general: jackson
    events: jackson
    messages: jackson
  eventhandling:
    processors:
      name:
        mode: tracking
        source: eventBus

axoniq:
  axonhub:
    servers: localhost

    axon:
      eventhandling:
        processors:
          name:
            mode=tracking:

